version: '3.8'

services:
  gateway:
    image: cleancadet/gateway:${GATEWAY_VERSION-latest}
    networks:
      - public
      - application
    ports:
      - "${GATEWAY_PUBLISHED_PORT-8080}:8080"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure


networks:
  public:
    name: clean_cadet_public_${STAGE-dev}
    driver: overlay
    attachable: true
  application:
    name: clean_cadet_application_${STAGE-dev}
    driver: overlay
    external: true