version: '3.8'

services:

  gateway:
    image: cleancadet/gateway:${GATEWAY_VERSION-latest}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - public
      - backend
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  smart-tutor:
    image: cleancadet/smart-tutor:${SMART_TUTOR_VERSION-latest}
    networks:
      - backend
      - database
    environment:
      STAGE: ${SMART_TUTOR_STAGE}
      DATABASE_HOST: ${SMART_TUTOR_DATABASE_HOST}
      DATABASE_PORT: ${SMART_TUTOR_DATABASE_PORT}
      DATABASE_SCHEMA: ${SMART_TUTOR_DATABASE_SCHEMA}
      DATABASE_USERNAME: ${SMART_TUTOR_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${SMART_TUTOR_DATABASE_PASSWORD}
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure

  database:
    image: postgres:${POSTGRES_VERSION-13}
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure


volumes:
  database-data:
    name: clean-cadet-database


networks:
  public:
    name: public
    driver: overlay 
  backend:
    name: backend
    driver: overlay
  database:
    name: database
    driver: overlay
